global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  #static_map: false
  static_map: true
  map_type: costmap
  resolution: 0.1
  #observation_sources: laser_scan_sensor

